// Crosswalk concept mappings — extracted from the component for maintainability.
// Each concept maps a bibliographic element across UNIMARC, MARC 21, Dublin Core, RDA, BIBFRAME.

export const CONCEPTS = [
  {
    id: "title",
    label: "Title",
    group: "descriptive",
    icon: "T",
    mappings: {
      unimarc: {
        field: "200 $a",
        label: "Title proper",
        match: "exact",
        note: "200 $a for title proper, $e for subtitle (parallel structure to MARC 21 245 $b), $d for parallel titles in other languages. IFLA standard requires transcription from the prescribed source of information. $h/$i for part numbering/naming.",
        indicators: [
          { pos: "1", label: "Title significance", values: "0 = Not significant; 1 = Significant (generates added entry)" },
          { pos: "2", label: "Undefined", values: "# (blank)" },
        ],
        subfields: [
          { code: "$a", desc: "Title proper (NR)" },
          { code: "$b", desc: "General material designation (NR)" },
          { code: "$c", desc: "Title proper by another author (R)" },
          { code: "$d", desc: "Parallel title proper (R)", note: "Titles in other languages" },
          { code: "$e", desc: "Other title information (R)", note: "Subtitle" },
          { code: "$f", desc: "First statement of responsibility (NR)" },
          { code: "$g", desc: "Subsequent statement of responsibility (R)" },
          { code: "$h", desc: "Number of a part (R)" },
          { code: "$i", desc: "Name of a part (R)" },
        ],
      },
      marc21: {
        field: "245 $a, $b",
        label: "Title statement",
        match: "exact",
        note: "245 $a for title proper, $b for remainder of title. Related fields: 210 (Abbreviated Title, R), 222 (Key Title, R), 240 (Uniform Title, NR), 242 (Translation of Title, R), 243 (Collective Uniform Title, NR), 246 (Varying Form of Title, R), 247 (Former Title, R).",
        indicators: [
          { pos: "1", label: "Title added entry", values: "0 = No added entry; 1 = Added entry" },
          { pos: "2", label: "Nonfiling characters", values: "0-9 (number of characters to skip for filing)" },
        ],
        subfields: [
          { code: "$a", desc: "Title (NR)" },
          { code: "$b", desc: "Remainder of title (NR)", note: "Subtitle and parallel titles" },
          { code: "$c", desc: "Statement of responsibility (NR)" },
          { code: "$f", desc: "Inclusive dates (NR)" },
          { code: "$g", desc: "Bulk dates (NR)" },
          { code: "$h", desc: "Medium [GMD] (NR)" },
          { code: "$k", desc: "Form (R)" },
          { code: "$n", desc: "Number of part/section (R)" },
          { code: "$p", desc: "Name of part/section (R)" },
          { code: "$s", desc: "Version (NR)" },
        ],
      },
      dc: {
        field: "dc:title",
        label: "Title",
        match: "lossy",
        note: "All title types collapse into one flat dc:title. Qualified DC adds dcterms:alternative but still loses the structured relationship between title/subtitle/parallel titles.",
        elements: [
          { code: "dc:title", desc: "A name given to the resource" },
          { code: "dcterms:alternative", desc: "An alternative name (Qualified DC only)" },
        ],
      },
      rda: {
        field: "RDA 2.3.2",
        label: "Title proper",
        match: "exact",
        note: "RDA provides granular title elements that map cleanly to and from MARC. Title proper is a core element.",
        elements: [
          { code: "2.3.2", desc: "Title proper (Core element)" },
          { code: "2.3.3", desc: "Parallel title proper" },
          { code: "2.3.4", desc: "Other title information (subtitle)" },
          { code: "2.3.5", desc: "Parallel other title information" },
          { code: "2.3.6", desc: "Variant title" },
          { code: "2.3.7", desc: "Earlier title proper (serials)" },
          { code: "2.3.8", desc: "Later title proper (serials)" },
          { code: "2.3.9", desc: "Key title (serials)" },
        ],
      },
      bibframe: {
        field: "bf:Title / bf:mainTitle",
        label: "Title resource",
        match: "exact",
        note: "BIBFRAME models Title as a separate resource with typed properties. Structurally richer than MARC — supports linking and round-tripping.",
        elements: [
          { code: "bf:Title", desc: "Title class (superclass)" },
          { code: "bf:mainTitle", desc: "Title proper (literal)" },
          { code: "bf:subtitle", desc: "Other title information (literal)" },
          { code: "bf:partName", desc: "Name of part (literal)" },
          { code: "bf:partNumber", desc: "Number of part (literal)" },
          { code: "bf:ParallelTitle", desc: "Parallel title (subclass)" },
          { code: "bf:VariantTitle", desc: "Variant title (subclass)" },
          { code: "bf:AbbreviatedTitle", desc: "Abbreviated title (subclass)" },
          { code: "bf:KeyTitle", desc: "Key title for serials (subclass)" },
        ],
      },
    },
    systemNotes: [
      {
        system: "Koha → Libris XL",
        issue: "When migrating from Koha (MARC 21) to Libris XL, 245 $b subtitle handling can vary. Libris XL expects clean separation; Koha sometimes stores subtitle with leading punctuation that needs stripping.",
      },
      {
        system: "UNIMARC → MARC 21 (Alma)",
        issue: "Alma's UNIMARC-to-MARC 21 crosswalk maps 200 $a → 245 $a correctly, but 200 $e (subtitle) → 245 $b sometimes drops the space-colon-space punctuation convention, requiring manual ISBD cleanup.",
      },
    ],
    realWorldExamples: [
      {
        scenario: "Multilingual title in Portuguese cataloging",
        problem: "A Portuguese/English bilingual resource cataloged in UNIMARC uses 200 $a for Portuguese title and 200 $d for English parallel title. Converting to Dublin Core loses the language distinction entirely — both become dc:title with no way to indicate which is primary.",
        impact: "Discovery systems may display the wrong language title to users, or concatenate both titles into an unreadable string.",
      },
    ],
  },
  {
    id: "creator",
    label: "Creator / Author",
    group: "descriptive",
    icon: "A",
    mappings: {
      unimarc: {
        field: "700 $a / 710 $a",
        label: "Personal / Corporate name",
        match: "exact",
        note: "700 (NR) for main entry personal name. 701 (R) for alternative responsibility, 702 (R) for secondary responsibility. 710/711/712 for corporate names.",
        indicators: [
          { pos: "1", label: "Undefined", values: "# (blank)" },
          { pos: "2", label: "Form of name", values: "0 = Forename entry; 1 = Surname entry" },
        ],
        subfields: [
          { code: "$a", desc: "Entry element (NR)", note: "Surname or single name" },
          { code: "$b", desc: "Part of name other than entry element (NR)" },
          { code: "$c", desc: "Additions to name other than dates (R)" },
          { code: "$d", desc: "Roman numerals (NR)" },
          { code: "$f", desc: "Dates (NR)" },
          { code: "$g", desc: "Expansion of initials (NR)" },
          { code: "$p", desc: "Affiliation/address (NR)" },
          { code: "$3", desc: "Authority record identifier (NR)" },
          { code: "$4", desc: "Relator code (R)", note: "070=author, 730=translator, 440=illustrator" },
        ],
      },
      marc21: {
        field: "100 $a / 110 $a",
        label: "Main entry — name",
        match: "exact",
        note: "100 (NR) for personal, 110 (NR) for corporate, 111 (NR) for meeting. 700/710/711 (R) for additional entries. All share similar subfield structure.",
        indicators: [
          { pos: "1", label: "Type of personal name", values: "0 = Forename; 1 = Surname; 3 = Family name" },
          { pos: "2", label: "Undefined", values: "# (blank)" },
        ],
        subfields: [
          { code: "$a", desc: "Personal name (NR)" },
          { code: "$b", desc: "Numeration (NR)" },
          { code: "$c", desc: "Titles and words associated with name (R)" },
          { code: "$d", desc: "Dates associated with name (NR)" },
          { code: "$e", desc: "Relator term (R)", note: "e.g., author, editor" },
          { code: "$q", desc: "Fuller form of name (NR)" },
          { code: "$u", desc: "Affiliation (NR)" },
          { code: "$0", desc: "Authority record control number or URI (R)" },
          { code: "$1", desc: "Real World Object URI (R)" },
          { code: "$4", desc: "Relator code (R)", note: "MARC relator code list" },
        ],
      },
      dc: {
        field: "dc:creator / dc:contributor",
        label: "Creator",
        match: "lossy",
        note: "Merges all name types into flat text. No personal vs. corporate distinction. Role info is lost unless using MARC relator refinements.",
        elements: [
          { code: "dc:creator", desc: "Entity primarily responsible for making the resource" },
          { code: "dc:contributor", desc: "Entity responsible for contributions" },
          { code: "marcrel:*", desc: "MARC relator refinements (Qualified DC)", note: "e.g., marcrel:trl for translator — rarely used" },
        ],
      },
      rda: {
        field: "RDA 19.2 / 20.2",
        label: "Creator / Contributor",
        match: "exact",
        note: "RDA clearly distinguishes creator from contributor and uses relationship designators from Appendix I.",
        elements: [
          { code: "19.2", desc: "Creator (Core element)" },
          { code: "19.3", desc: "Other person/family/corporate body associated with a work" },
          { code: "20.2", desc: "Contributor" },
          { code: "Appendix I", desc: "Relationship designators", note: "author, editor, compiler, translator, illustrator, etc." },
        ],
      },
      bibframe: {
        field: "bf:contribution / bf:agent",
        label: "Contribution",
        match: "exact",
        note: "BIBFRAME models this as a Contribution resource linking an Agent to a Work/Instance with a role. The agent is a separate linked resource.",
        elements: [
          { code: "bf:Contribution", desc: "Contribution class (links agent + role)" },
          { code: "bf:agent", desc: "Agent resource (bf:Person, bf:Organization, bf:Meeting)" },
          { code: "bf:role", desc: "Role resource (links to relator URI)" },
          { code: "bf:PrimaryContribution", desc: "Subclass for main entry equivalent" },
        ],
      },
    },
    systemNotes: [
      {
        system: "Koha",
        issue: "Koha's authority module links 100/700 to authority records. When exporting to Dublin Core (OAI-PMH), the link is broken and only the text string is exported, losing the authority control.",
      },
      {
        system: "Libris XL",
        issue: "Libris XL uses linked data internally. Agent names are URIs pointing to KB's authority files. Exporting to MARC 21 flattens these back to text strings in $a, but the $0 subfield may carry the URI.",
      },
    ],
    realWorldExamples: [
      {
        scenario: "Converting a UNIMARC record with multiple roles",
        problem: "A UNIMARC record for a translated illustrated children's book has 700 entries with $4 codes for author (070), translator (730), and illustrator (440). Converting to Dublin Core produces three dc:contributor entries with no role information — you cannot tell who wrote, translated, or illustrated the book.",
        impact: "Libraries using Dublin Core for cross-collection search cannot properly attribute works or filter by role.",
      },
    ],
  },
  {
    id: "publisher",
    label: "Publisher / Publication",
    group: "descriptive",
    icon: "P",
    mappings: {
      unimarc: {
        field: "210 $a, $c, $d",
        label: "Publication, distribution",
        match: "exact",
        note: "210 (NR) for publication/distribution. IFLA ISBD punctuation applies. Field 214 may be used instead in RDA-aligned records (2017 UNIMARC update).",
        indicators: [
          { pos: "1", label: "Undefined", values: "# (blank)" },
          { pos: "2", label: "Undefined", values: "# (blank)" },
        ],
        subfields: [
          { code: "$a", desc: "Place of publication/distribution (R)" },
          { code: "$b", desc: "Address of publisher/distributor (R)" },
          { code: "$c", desc: "Name of publisher/distributor (R)" },
          { code: "$d", desc: "Date of publication/distribution (NR)" },
          { code: "$e", desc: "Place of manufacture (R)" },
          { code: "$g", desc: "Name of manufacturer (R)" },
          { code: "$h", desc: "Date of manufacture (NR)" },
        ],
      },
      marc21: {
        field: "264 $a, $b, $c",
        label: "Production, publication",
        match: "exact",
        note: "264 (R) replaced 260 for RDA records. The second indicator distinguishes function — a key structural advantage over UNIMARC 210. 260 still valid for AACR2 records.",
        indicators: [
          { pos: "1", label: "Sequence of statements", values: "# = Not applicable; 2 = Intervening; 3 = Current/latest" },
          { pos: "2", label: "Function of entity", values: "0 = Production; 1 = Publication; 2 = Distribution; 3 = Manufacture; 4 = Copyright notice date" },
        ],
        subfields: [
          { code: "$a", desc: "Place (R)" },
          { code: "$b", desc: "Name of producer/publisher/distributor/manufacturer (R)" },
          { code: "$c", desc: "Date (R)" },
          { code: "$3", desc: "Materials specified (NR)" },
        ],
      },
      dc: {
        field: "dc:publisher",
        label: "Publisher",
        match: "lossy",
        note: "Only captures publisher name. Place requires a separate element. The structured MARC relationship between place-publisher-date is destroyed.",
        elements: [
          { code: "dc:publisher", desc: "Entity responsible for making resource available" },
          { code: "dcterms:issued", desc: "Date of formal issuance (Qualified DC)" },
          { code: "dcterms:spatial", desc: "Used for place — but conflates with geographic coverage" },
        ],
      },
      rda: {
        field: "RDA 2.8",
        label: "Publication statement",
        match: "exact",
        note: "RDA 2.8.2 (place), 2.8.4 (publisher name), 2.8.6 (date). Clearly separated elements that map cleanly to and from MARC 264.",
      },
      bibframe: {
        field: "bf:provisionActivity",
        label: "Provision activity",
        match: "exact",
        note: "Type (publication/distribution/manufacture) captured as a class. Each activity has place, agent, and date properties.",
        elements: [
          { code: "bf:ProvisionActivity", desc: "Superclass" },
          { code: "bf:Publication", desc: "Publication activity (subclass)" },
          { code: "bf:Distribution", desc: "Distribution activity (subclass)" },
          { code: "bf:Manufacture", desc: "Manufacture activity (subclass)" },
          { code: "bf:place", desc: "Place of activity (property)" },
          { code: "bf:agent", desc: "Agent of activity (property)" },
          { code: "bf:date", desc: "Date of activity (property)" },
          { code: "bf:copyrightDate", desc: "Copyright date (on Instance)" },
        ],
      },
    },
    systemNotes: [
      {
        system: "Koha (MARC 21)",
        issue: "Koha supports both 260 and 264 but some older templates still default to 260. Records created with 260 may not display correctly in OPAC views configured for 264.",
      },
      {
        system: "Libris XL",
        issue: "Libris XL maps publication data to linked data properties. When round-tripping back to MARC 21, the place of publication sometimes loses the $a subfield coding if the linked data property was ambiguous.",
      },
    ],
    realWorldExamples: [
      {
        scenario: "260 vs 264 coexistence",
        problem: "A library migrating from AACR2 to RDA has a mixed catalog with some records using 260 and others using 264. OAI-PMH export to Dublin Core maps both to dc:publisher, but the extraction logic may only look for one field, silently losing publisher data for half the records.",
        impact: "Aggregators like Europeana may receive records with missing publisher information.",
      },
    ],
  },
  {
    id: "date",
    label: "Date",
    group: "descriptive",
    icon: "D",
    mappings: {
      unimarc: {
        field: "210 $d / 100 $a pos. 9-16",
        label: "Date of publication",
        match: "exact",
        note: "Display date in 210 $d; coded dates in field 100 $a. IFLA standard requires coded dates even when display date is approximate.",
        subfields: [
          { code: "210 $d", desc: "Date of publication/distribution (NR)", note: "Display form, may include brackets" },
          { code: "100 pos.8", desc: "Type of date code", note: "a=current; b=between dates; d=detailed; e=reprint; f=uncertain; g=serial ranges" },
          { code: "100 pos.9-12", desc: "Date 1 (YYYY)" },
          { code: "100 pos.13-16", desc: "Date 2 (YYYY)", note: "Context depends on pos.8" },
        ],
      },
      marc21: {
        field: "264 $c / 008 pos. 7-14",
        label: "Date of publication",
        match: "exact",
        note: "264 $c for display date; 008 for coded dates. Functionally equivalent to UNIMARC 100.",
        subfields: [
          { code: "264 $c", desc: "Date of publication (R)" },
          { code: "008/06", desc: "Type of date/Publication status", note: "s=single; m=multiple; r=reprint; t=pub+copyright; q=questionable; n=unknown" },
          { code: "008/07-10", desc: "Date 1 (YYYY)", note: "u for unknown digit" },
          { code: "008/11-14", desc: "Date 2 (YYYY)", note: "Depends on 008/06 code" },
        ],
      },
      dc: {
        field: "dc:date",
        label: "Date",
        match: "lossy",
        note: "All date types collapse into dc:date. Qualified DC offers more options but doesn't cover all MARC date types (reprint, questionable, multiple).",
        elements: [
          { code: "dc:date", desc: "A point or period of time" },
          { code: "dcterms:created", desc: "Date of creation (Qualified DC)" },
          { code: "dcterms:issued", desc: "Date of formal issuance (Qualified DC)" },
          { code: "dcterms:modified", desc: "Date resource was changed (Qualified DC)" },
          { code: "dcterms:dateCopyrighted", desc: "Copyright date (Qualified DC)" },
        ],
      },
      rda: {
        field: "RDA 2.8.6 / 2.11",
        label: "Date of publication / Copyright date",
        match: "exact",
        note: "RDA separates each date type. Clean mapping to MARC 264 $c with different indicators.",
        elements: [
          { code: "2.7.6", desc: "Date of production" },
          { code: "2.8.6", desc: "Date of publication (Core)" },
          { code: "2.9.6", desc: "Date of distribution" },
          { code: "2.10.6", desc: "Date of manufacture" },
          { code: "2.11", desc: "Copyright date" },
        ],
      },
      bibframe: {
        field: "bf:provisionActivity / bf:date",
        label: "Date",
        match: "exact",
        note: "Date is a property of the ProvisionActivity resource. Copyright date has its own property on Instance.",
        elements: [
          { code: "bf:date", desc: "Date property on ProvisionActivity" },
          { code: "bf:copyrightDate", desc: "Copyright date (property on Instance)" },
          { code: "bf:originDate", desc: "Date of origin (property on Work)" },
        ],
      },
    },
    systemNotes: [
      {
        system: "Koha → Dublin Core export",
        issue: "Koha's OAI-PMH server maps 260/264 $c to dc:date but does not extract the coded date from 008. Records with coded dates but no $c display date export with empty dc:date.",
      },
    ],
    realWorldExamples: [
      {
        scenario: "Multi-volume work spanning decades",
        problem: "A MARC 21 record for a multi-volume encyclopedia uses 008/06='m' (multiple dates) with Date 1=1995 and Date 2=2003. Converting to Dublin Core produces dc:date='1995' — the end date and the fact that this spans 8 years is lost entirely.",
        impact: "Users searching for resources from 2000-2003 will not find this work.",
      },
    ],
  },
  {
    id: "identifier",
    label: "Identifier",
    group: "descriptive",
    icon: "ID",
    mappings: {
      unimarc: {
        field: "010 $a / 011 $a / 001",
        label: "ISBN / ISSN / Record ID",
        match: "exact",
        note: "IFLA UNIMARC assigns a dedicated field to each identifier type — no ambiguity.",
        indicators: [
          { pos: "010 ind", label: "Undefined", values: "# # (blank)" },
        ],
        subfields: [
          { code: "010 $a", desc: "ISBN number (NR)" },
          { code: "010 $b", desc: "Qualification (NR)", note: "e.g., bound, paperback" },
          { code: "010 $d", desc: "Terms of availability/price (NR)" },
          { code: "010 $z", desc: "Erroneous ISBN (R)" },
          { code: "011 $a", desc: "ISSN number (NR)" },
          { code: "011 $y", desc: "Cancelled ISSN (R)" },
          { code: "011 $z", desc: "Erroneous ISSN (R)" },
          { code: "012 $a", desc: "Fingerprint (NR)" },
          { code: "071 $a", desc: "Publisher's number (NR)", note: "Music, sound recordings" },
        ],
      },
      marc21: {
        field: "020 $a / 022 $a / 001",
        label: "ISBN / ISSN / Control number",
        match: "exact",
        note: "Each identifier type has its own field. 024 covers DOI, URN, ISRC and others via first indicator.",
        indicators: [
          { pos: "020 ind", label: "Undefined", values: "# # (blank)" },
          { pos: "022 ind1", label: "Level of international interest", values: "# = No level; 0 = International interest; 1 = Not international" },
          { pos: "024 ind1", label: "Type of number", values: "0=ISRC; 1=UPC; 2=ISMN; 3=EAN; 4=SICI; 7=source in $2; 8=unspecified" },
        ],
        subfields: [
          { code: "020 $a", desc: "ISBN (NR)" },
          { code: "020 $q", desc: "Qualifying information (R)", note: "Binding, volume" },
          { code: "020 $z", desc: "Canceled/invalid ISBN (R)" },
          { code: "022 $a", desc: "ISSN (NR)" },
          { code: "022 $l", desc: "ISSN-L (NR)" },
          { code: "022 $y", desc: "Incorrect ISSN (R)" },
          { code: "024 $a", desc: "Standard number or code (NR)" },
          { code: "024 $2", desc: "Source of number (NR)", note: "When ind1=7" },
        ],
      },
      dc: {
        field: "dc:identifier",
        label: "Identifier",
        match: "lossy",
        note: "All identifier types merge into dc:identifier. No structural way to distinguish ISBN from ISSN from DOI.",
        elements: [
          { code: "dc:identifier", desc: "Unambiguous reference to the resource" },
          { code: "dcterms:bibliographicCitation", desc: "Bibliographic reference (Qualified DC)", note: "Rarely used for standard numbers" },
        ],
      },
      rda: {
        field: "RDA 2.15",
        label: "Identifier for the manifestation",
        match: "exact",
        note: "RDA 2.15 covers all identifiers with type specification. Maps directly to MARC fields.",
        elements: [
          { code: "2.15", desc: "Identifier for the manifestation (Core)" },
          { code: "2.15.1.4", desc: "Recording identifiers — record with type" },
          { code: "6.8", desc: "Identifier for the work" },
        ],
      },
      bibframe: {
        field: "bf:identifiedBy",
        label: "Identified by",
        match: "exact",
        note: "Each identifier is a separate typed resource — structurally superior to both MARC and Dublin Core.",
        elements: [
          { code: "bf:Isbn", desc: "ISBN resource" },
          { code: "bf:Issn", desc: "ISSN resource" },
          { code: "bf:IssnL", desc: "ISSN-L resource" },
          { code: "bf:Doi", desc: "DOI resource" },
          { code: "bf:Lccn", desc: "LCCN resource" },
          { code: "bf:Local", desc: "Local identifier" },
          { code: "bf:Urn", desc: "URN resource" },
          { code: "bf:Status", desc: "For invalid/cancelled identifiers" },
        ],
      },
    },
    systemNotes: [
      {
        system: "UNIMARC → MARC 21",
        issue: "UNIMARC 010 maps to MARC 21 020 cleanly, but UNIMARC 010 $b (binding qualifier) has no standard MARC 21 equivalent — it gets mapped to 020 $q in recent practice, but older conversions dropped it.",
      },
      {
        system: "Libris XL",
        issue: "Libris XL stores ISBNs as linked data with the bf:Isbn type. When exporting MARC 21, ISBNs without hyphens are normalized. Records imported with hyphens may export without them, causing comparison mismatches.",
      },
    ],
    realWorldExamples: [
      {
        scenario: "Multiple ISBNs for different formats",
        problem: "A MARC 21 record has three 020 fields: hardcover ISBN, paperback ISBN, and e-book ISBN, each with $q qualifiers. Converting to Dublin Core creates three dc:identifier strings with no way to tell which format each ISBN represents.",
        impact: "Link resolvers cannot determine which ISBN corresponds to the user's desired format.",
      },
    ],
  },
  {
    id: "edition",
    label: "Edition",
    group: "descriptive",
    icon: "E",
    mappings: {
      unimarc: {
        field: "205 - Edition Statement (R)",
        label: "Edition statement",
        match: "exact",
        note: "Repeatable for multiple edition statements. Transcribed from prescribed source.",
        indicators: [
          { pos: "1", label: "Undefined", values: "# (blank)" },
          { pos: "2", label: "Undefined", values: "# (blank)" },
        ],
        subfields: [
          { code: "$a", desc: "Edition statement (NR)" },
          { code: "$b", desc: "Additional edition statement (NR)" },
          { code: "$d", desc: "Parallel edition statement (R)" },
          { code: "$f", desc: "Statement of responsibility relating to the edition (NR)" },
          { code: "$g", desc: "Subsequent statement of responsibility (R)" },
        ],
      },
      marc21: {
        field: "250 - Edition Statement (R)",
        label: "Edition statement",
        match: "exact",
        note: "Transcribed from resource. Made repeatable in 2019 (previously NR). Related: 254 (Musical Presentation Statement, NR).",
        indicators: [
          { pos: "1", label: "Undefined", values: "# (blank)" },
          { pos: "2", label: "Undefined", values: "# (blank)" },
        ],
        subfields: [
          { code: "$a", desc: "Edition statement (NR)" },
          { code: "$b", desc: "Remainder of edition statement (NR)", note: "Includes statement of responsibility relating to edition" },
          { code: "$3", desc: "Materials specified (NR)" },
          { code: "$6", desc: "Linkage (NR)" },
        ],
      },
      dc: {
        field: "No dedicated element",
        label: "No standard mapping",
        match: "lossy",
        note: "Dublin Core has no edition element. Edition info may go into dc:description or be appended to dc:title. Some implementations use dc:hasVersion or dcterms:isVersionOf but these describe version relationships, not edition statements.",
        elements: [
          { code: "dc:description", desc: "Used as fallback for edition info" },
          { code: "dcterms:hasVersion", desc: "Version relationship (not edition statement)" },
        ],
      },
      rda: {
        field: "RDA 2.5 - Edition Statement",
        label: "Edition statement",
        match: "exact",
        note: "RDA 2.5 covers edition statement as a core element when applicable. Includes designation and statement of responsibility.",
        elements: [
          { code: "2.5.2", desc: "Designation of edition (Core when applicable)" },
          { code: "2.5.4", desc: "Statement of responsibility relating to the edition" },
          { code: "2.5.6", desc: "Designation of a named revision of an edition" },
          { code: "2.5.8", desc: "Statement of responsibility relating to a named revision" },
        ],
      },
      bibframe: {
        field: "bf:editionStatement",
        label: "Edition statement",
        match: "exact",
        note: "Simple literal property on bf:Instance. Less structured than MARC — no separate subfields for responsibility.",
        elements: [
          { code: "bf:editionStatement", desc: "Edition statement (literal, on Instance)" },
          { code: "bf:editionEnumeration", desc: "Edition enumeration (literal)" },
        ],
      },
    },
    systemNotes: [
      { system: "Koha", issue: "Koha displays 250 in OPAC but older templates may not display $b (remainder of edition statement) separately. The full ISBD punctuation in $a/$b can appear doubled if the template adds its own punctuation." },
      { system: "Libris XL", issue: "Libris XL stores edition statement as a simple text property on Instance (Utgåva). When exporting to MARC 21, it maps cleanly to 250 $a, but if the original record had separate $a/$b, the subfield boundary may be lost." },
    ],
    realWorldExamples: [
      {
        scenario: "Edition statement lost in Dublin Core export",
        problem: "A textbook in its '5th revised and expanded edition' is exported to Dublin Core for a repository. Since DC has no edition element, the information is either silently dropped or dumped into dc:description where it's not searchable as structured data.",
        impact: "Users cannot filter or sort by edition in aggregators that rely on Dublin Core.",
      },
    ],
  },
  {
    id: "physical",
    label: "Physical Description",
    group: "descriptive",
    icon: "Ph",
    mappings: {
      unimarc: {
        field: "215 - Physical Description (R)",
        label: "Physical description",
        match: "exact",
        note: "Covers extent, illustrations, dimensions, and accompanying material. Follows ISBD area 5 conventions.",
        indicators: [
          { pos: "1", label: "Undefined", values: "# (blank)" },
          { pos: "2", label: "Undefined", values: "# (blank)" },
        ],
        subfields: [
          { code: "$a", desc: "Specific material designation and extent (R)", note: "e.g., 256 pages" },
          { code: "$c", desc: "Other physical details (R)", note: "Illustrations, colour, etc." },
          { code: "$d", desc: "Dimensions (R)", note: "e.g., 24 cm" },
          { code: "$e", desc: "Accompanying material (R)" },
        ],
      },
      marc21: {
        field: "300 - Physical Description (R)",
        label: "Physical description",
        match: "exact",
        note: "Covers extent, other physical details, dimensions, and accompanying material. Related: 306 (Playing Time), 340 (Physical Medium), 344-347 (Sound/Video/Digital Characteristics).",
        indicators: [
          { pos: "1", label: "Undefined", values: "# (blank)" },
          { pos: "2", label: "Undefined", values: "# (blank)" },
        ],
        subfields: [
          { code: "$a", desc: "Extent (R)", note: "e.g., 256 pages, 1 online resource" },
          { code: "$b", desc: "Other physical details (NR)", note: "Illustrations, colour, sound, etc." },
          { code: "$c", desc: "Dimensions (R)", note: "e.g., 24 cm" },
          { code: "$e", desc: "Accompanying material (NR)" },
          { code: "$f", desc: "Type of unit (R)" },
          { code: "$g", desc: "Size of unit (R)" },
          { code: "$3", desc: "Materials specified (NR)" },
        ],
      },
      dc: {
        field: "dc:format",
        label: "Format",
        match: "lossy",
        note: "dc:format captures media type or extent but not the structured physical description. Dimensions, illustrations, and accompanying material have no dedicated elements.",
        elements: [
          { code: "dc:format", desc: "File format, physical medium, or dimensions" },
          { code: "dcterms:extent", desc: "Size or duration (Qualified DC)" },
          { code: "dcterms:medium", desc: "Material or physical carrier (Qualified DC)" },
        ],
      },
      rda: {
        field: "RDA 3.4 / 3.5 / 7.15 / 7.17",
        label: "Carrier and content description",
        match: "exact",
        note: "RDA distributes physical description across multiple elements. Extent is a core element for tangible resources.",
        elements: [
          { code: "3.4", desc: "Extent (Core for tangible resources)" },
          { code: "3.5", desc: "Dimensions" },
          { code: "7.15", desc: "Illustrative content" },
          { code: "7.17", desc: "Colour content" },
          { code: "3.21", desc: "Supplementary content", note: "Accompanying material" },
        ],
      },
      bibframe: {
        field: "bf:extent / bf:dimensions",
        label: "Physical description properties",
        match: "exact",
        note: "BIBFRAME separates each aspect into its own property on Instance. More granular than MARC 300.",
        elements: [
          { code: "bf:extent", desc: "Extent (property on Instance)" },
          { code: "bf:dimensions", desc: "Dimensions (literal on Instance)" },
          { code: "bf:illustrativeContent", desc: "Illustrative content (on Work)" },
          { code: "bf:colorContent", desc: "Colour content (on Work)" },
          { code: "bf:supplementaryContent", desc: "Supplementary content (on Work)" },
          { code: "bf:SupplementaryContent", desc: "Supplementary content class" },
        ],
      },
    },
    systemNotes: [
      { system: "Koha", issue: "Koha's 300 $a is used for OPAC display and also feeds the 'pages' facet in Elasticsearch-based catalogs. If extent is entered inconsistently (e.g., 'ca 250 s.' vs '250 pages'), faceting breaks." },
      { system: "Libris XL", issue: "Libris XL stores extent as a structured property (Omfång) on Instance. Swedish practice uses 'sidor' (pages) or 's.' abbreviation. Export to MARC 21 maps to 300 $a but may not match international conventions." },
    ],
    realWorldExamples: [
      {
        scenario: "Physical description in a digital-first world",
        problem: "A library catalogs both a print book (300 $a '328 pages' $c '22 cm') and its e-book equivalent (300 $a '1 online resource'). When both are exported to Dublin Core, both get dc:format but the rich physical description of the print edition is flattened into a single string.",
        impact: "Users cannot distinguish between physical and digital manifestations in aggregated search results.",
      },
    ],
  },
  {
    id: "series",
    label: "Series",
    group: "descriptive",
    icon: "Se",
    mappings: {
      unimarc: {
        field: "225 - Series (R)",
        label: "Series",
        match: "exact",
        note: "Series title as it appears on the resource. Field 410 used for series tracing (linked to authority).",
        indicators: [
          { pos: "1", label: "Undefined", values: "# (blank)" },
          { pos: "2", label: "Series note", values: "# = Series note; 0 = No series note; 1 = Uncontrolled note; 2 = Controlled note" },
        ],
        subfields: [
          { code: "$a", desc: "Series title (NR)" },
          { code: "$d", desc: "Parallel series title (R)" },
          { code: "$e", desc: "Other title information (R)", note: "Series subtitle" },
          { code: "$f", desc: "Statement of responsibility (NR)" },
          { code: "$h", desc: "Number of a part (R)" },
          { code: "$i", desc: "Name of a part (R)" },
          { code: "$v", desc: "Volume designation (NR)" },
          { code: "$x", desc: "ISSN of series (NR)" },
        ],
      },
      marc21: {
        field: "490 - Series Statement (R)",
        label: "Series statement",
        match: "exact",
        note: "Series as it appears on the resource. First indicator controls whether an 8XX series added entry is present. Related: 800-830 (Series Added Entry fields) for authorized form.",
        indicators: [
          { pos: "1", label: "Series tracing policy", values: "0 = Series not traced; 1 = Series traced (8XX present)" },
          { pos: "2", label: "Undefined", values: "# (blank)" },
        ],
        subfields: [
          { code: "$a", desc: "Series statement (R)" },
          { code: "$l", desc: "Library of Congress call number (NR)" },
          { code: "$v", desc: "Volume/sequential designation (R)" },
          { code: "$x", desc: "ISSN of series (R)" },
          { code: "$3", desc: "Materials specified (NR)" },
        ],
      },
      dc: {
        field: "dc:relation.isPartOf",
        label: "Is Part Of",
        match: "partial",
        note: "Series can be expressed as dc:relation with dcterms:isPartOf qualifier. But the volume number, ISSN, and subseries structure are lost. Many implementations simply ignore series.",
        elements: [
          { code: "dcterms:isPartOf", desc: "Related resource the described resource is part of" },
          { code: "dc:relation", desc: "Generic related resource (unqualified DC)" },
        ],
      },
      rda: {
        field: "RDA 2.12 - Series Statement",
        label: "Series statement",
        match: "exact",
        note: "RDA treats series statement as a core element when applicable. Includes title, numbering, and sub-series.",
        elements: [
          { code: "2.12.2", desc: "Title proper of series (Core when applicable)" },
          { code: "2.12.4", desc: "Parallel title of series" },
          { code: "2.12.6", desc: "Other title information of series" },
          { code: "2.12.8", desc: "Statement of responsibility of series" },
          { code: "2.12.9", desc: "ISSN of series" },
          { code: "2.12.10", desc: "Numbering within series" },
          { code: "2.12.12-17", desc: "Subseries elements (parallel structure)" },
        ],
      },
      bibframe: {
        field: "bf:hasSeries / bf:seriesStatement",
        label: "Series",
        match: "exact",
        note: "BIBFRAME can model series as a linked resource (bf:hasSeries linking to another bf:Instance) or as a simple literal (bf:seriesStatement). The linked approach is richer.",
        elements: [
          { code: "bf:hasSeries", desc: "Links to series Instance resource" },
          { code: "bf:seriesStatement", desc: "Series statement as literal text" },
          { code: "bf:seriesEnumeration", desc: "Volume/number within series" },
        ],
      },
    },
    systemNotes: [
      { system: "Koha", issue: "Koha handles 490/8XX series linking through the authority module. If 490 ind1=1 but no matching 800-830 exists, the series displays in OPAC but isn't linked or browsable as a series." },
      { system: "Libris XL", issue: "Libris XL models series as a linked Instans (seriemedlemskap). The series title links to a series authority. Export to MARC 21 generates both 490 and 830, but the $v volume numbering can be inconsistent between the two." },
    ],
    realWorldExamples: [
      {
        scenario: "Series lost in Dublin Core harvesting",
        problem: "A monograph in the series 'Cambridge Studies in Linguistics ; 145' is exported via OAI-PMH. The aggregator receives dcterms:isPartOf with the series title but the volume number '145' is lost. The ISSN of the series is not transmitted either.",
        impact: "Users cannot determine the volume's position within the series or verify the series through its ISSN.",
      },
    ],
  },
  {
    id: "language",
    label: "Language",
    group: "descriptive",
    icon: "L",
    mappings: {
      unimarc: {
        field: "101 - Language of the Item (NR)",
        label: "Language of the item",
        match: "exact",
        note: "Coded language field. Uses ISO 639-2 three-letter codes. Covers text language, original language, and intermediary translation language.",
        indicators: [
          { pos: "1", label: "Translation indicator", values: "0 = Item is in its original language; 1 = Item is a translation; 2 = Contains translations other than summaries" },
          { pos: "2", label: "Undefined", values: "# (blank)" },
        ],
        subfields: [
          { code: "$a", desc: "Language of text (R)", note: "ISO 639-2 code" },
          { code: "$b", desc: "Language of intermediary text (R)", note: "When translation is indirect" },
          { code: "$c", desc: "Language of original work (R)" },
          { code: "$d", desc: "Language of summary (R)" },
          { code: "$g", desc: "Language of original title on title page (NR)" },
          { code: "$h", desc: "Language of libretto (R)" },
          { code: "$j", desc: "Language of subtitles (R)" },
        ],
      },
      marc21: {
        field: "008/35-37 + 041 - Language Code (R)",
        label: "Language code",
        match: "exact",
        note: "008/35-37 for primary language (fixed field). 041 for detailed language coding when item involves multiple languages or translations. Uses MARC language code list.",
        indicators: [
          { pos: "041 ind1", label: "Translation indicator", values: "# = No info; 0 = Not a translation; 1 = Translation or includes a translation" },
          { pos: "041 ind2", label: "Source of code", values: "# = MARC language code; 7 = Source in $2" },
        ],
        subfields: [
          { code: "008/35-37", desc: "Language (fixed field)", note: "Three-letter MARC code" },
          { code: "041 $a", desc: "Language code of text (R)" },
          { code: "041 $b", desc: "Language code of summary (R)" },
          { code: "041 $d", desc: "Language code of sung/spoken text (R)" },
          { code: "041 $h", desc: "Language code of original (R)" },
          { code: "041 $j", desc: "Language code of subtitles (R)" },
          { code: "041 $k", desc: "Language code of intermediary translations (R)" },
          { code: "041 $2", desc: "Source of code (NR)", note: "e.g., iso639-2b" },
        ],
      },
      dc: {
        field: "dc:language",
        label: "Language",
        match: "partial",
        note: "dc:language captures the language of the resource. Single element — no way to distinguish between text language, original language, summary language, or subtitle language. RFC 4646 or ISO 639 codes recommended.",
        elements: [
          { code: "dc:language", desc: "Language of the resource" },
          { code: "dcterms:RFC4646", desc: "Encoding scheme (Qualified DC)" },
          { code: "dcterms:ISO639-2", desc: "Encoding scheme (Qualified DC)" },
        ],
      },
      rda: {
        field: "RDA 7.12 / 7.14",
        label: "Language of content",
        match: "exact",
        note: "RDA treats language of expression as a core element. Separate elements for different language roles.",
        elements: [
          { code: "7.12", desc: "Language of the content (Core)" },
          { code: "7.14", desc: "Accessibility content", note: "Includes language of subtitles, audio description" },
          { code: "6.11", desc: "Language of expression (on Expression)" },
          { code: "24.6", desc: "Language of expression used as access point qualifier" },
        ],
      },
      bibframe: {
        field: "bf:language",
        label: "Language",
        match: "exact",
        note: "bf:language links to a Language resource (typically using URI from id.loc.gov). Can express multiple languages and their roles (text, original, summary).",
        elements: [
          { code: "bf:language", desc: "Language property (on Work)" },
          { code: "bf:Language", desc: "Language class" },
          { code: "bf:part", desc: "Part qualifier", note: "Specifies which part (summary, subtitle, etc.)" },
          { code: "bf:translationOf", desc: "Links to original language work" },
          { code: "bf:hasTranslation", desc: "Links to translated work" },
        ],
      },
    },
    systemNotes: [
      { system: "Koha", issue: "Koha uses 008/35-37 for the language facet in OPAC. If 041 contains multiple languages but 008 only has the primary, the facet won't reflect multilingual content. Swedish libraries cataloging bilingual works need both fields." },
      { system: "Libris XL", issue: "Libris XL stores language as a linked entity (Språk) using URIs from id.kb.se. Multiple languages are well-supported. Export to MARC 21 generates both 008/35-37 and 041, but the translation indicator (041 ind1) may default to '#' even for translations." },
    ],
    realWorldExamples: [
      {
        scenario: "Translation chain lost in crosswalk",
        problem: "A Swedish translation of a Japanese novel, translated via English as intermediary language. UNIMARC 101 captures this cleanly: $a swe $c jpn $b eng (ind1=1). MARC 21 041 handles it similarly with $a swe $h jpn $k eng. Converting to Dublin Core produces dc:language='swe' — the entire translation history is lost.",
        impact: "Researchers studying translation practices cannot trace intermediary languages in Dublin Core-based repositories.",
      },
    ],
  },
  {
    id: "contenttype",
    label: "Content / Media / Carrier",
    group: "descriptive",
    icon: "CMC",
    mappings: {
      unimarc: {
        field: "181/182/183 - Content/Media/Carrier Type",
        label: "Content, media, carrier type",
        match: "exact",
        note: "Introduced to align UNIMARC with RDA. 181 for content type, 182 for media type, 183 for carrier type. In older records, type info is in Leader/06-07 and 135 (Coded Data Field: Electronic Resources).",
        subfields: [
          { code: "181 $a", desc: "Content type code (R)", note: "From IFLA list" },
          { code: "181 $2", desc: "Source (NR)" },
          { code: "182 $a", desc: "Media type code (R)" },
          { code: "182 $2", desc: "Source (NR)" },
          { code: "183 $a", desc: "Carrier type code (R)" },
          { code: "183 $2", desc: "Source (NR)" },
        ],
      },
      marc21: {
        field: "336/337/338 - Content/Media/Carrier Type (R)",
        label: "Content, media, carrier type",
        match: "exact",
        note: "Core RDA elements since 2013. Replaced GMD (General Material Designation) in 245 $h. Each field uses controlled vocabulary from RDA/ONIX Framework.",
        indicators: [
          { pos: "336 ind", label: "Undefined", values: "# # (blank)" },
          { pos: "337 ind", label: "Undefined", values: "# # (blank)" },
          { pos: "338 ind", label: "Undefined", values: "# # (blank)" },
        ],
        subfields: [
          { code: "336 $a", desc: "Content type term (R)", note: "e.g., text, performed music, still image" },
          { code: "336 $b", desc: "Content type code (R)", note: "e.g., txt, prm, sti" },
          { code: "336 $2", desc: "Source (NR)", note: "rdacontent" },
          { code: "337 $a", desc: "Media type term (R)", note: "e.g., unmediated, computer, audio" },
          { code: "337 $b", desc: "Media type code (R)", note: "e.g., n, c, s" },
          { code: "337 $2", desc: "Source (NR)", note: "rdamedia" },
          { code: "338 $a", desc: "Carrier type term (R)", note: "e.g., volume, online resource, audio disc" },
          { code: "338 $b", desc: "Carrier type code (R)", note: "e.g., nc, cr, sd" },
          { code: "338 $2", desc: "Source (NR)", note: "rdacarrier" },
        ],
      },
      dc: {
        field: "dc:type / dc:format",
        label: "Type and format",
        match: "lossy",
        note: "Dublin Core conflates content type and carrier type into dc:type (DCMI Type Vocabulary) and dc:format (MIME types). The three-way RDA distinction (what it IS / how you ACCESS it / what it's ON) collapses into two coarse elements.",
        elements: [
          { code: "dc:type", desc: "Nature or genre (DCMI Type Vocabulary)", note: "Text, Image, Sound, etc." },
          { code: "dc:format", desc: "File format or physical medium", note: "MIME types or physical description" },
        ],
      },
      rda: {
        field: "RDA 6.9 / 3.2 / 3.3",
        label: "Content / Media / Carrier type",
        match: "exact",
        note: "These are core RDA elements. The three-way distinction is fundamental to the RDA framework and replaces the old GMD concept.",
        elements: [
          { code: "6.9", desc: "Content type (Core)", note: "text, performed music, cartographic image, etc." },
          { code: "3.2", desc: "Media type (Core)", note: "unmediated, computer, audio, video, etc." },
          { code: "3.3", desc: "Carrier type (Core)", note: "volume, online resource, audio disc, etc." },
        ],
      },
      bibframe: {
        field: "bf:content / bf:media / bf:carrier",
        label: "Content, media, carrier",
        match: "exact",
        note: "BIBFRAME mirrors the RDA three-way distinction. Each links to a controlled vocabulary resource.",
        elements: [
          { code: "bf:content", desc: "Content type (property on Work)" },
          { code: "bf:media", desc: "Media type (property on Instance)" },
          { code: "bf:carrier", desc: "Carrier type (property on Instance)" },
          { code: "bf:Content", desc: "Content type class" },
          { code: "bf:Media", desc: "Media type class" },
          { code: "bf:Carrier", desc: "Carrier type class" },
        ],
      },
    },
    systemNotes: [
      { system: "Koha", issue: "Koha introduced support for 336/337/338 display in recent versions, but many Swedish library Koha installations still use older templates that display 245 $h (GMD) instead. Records with 336/337/338 but no 245 $h show no material type in older OPACs." },
      { system: "Libris XL", issue: "Libris XL uses content/media/carrier types as core structured properties (Innehållstyp, Mediatyp, Bärartyp). These map directly to MARC 336/337/338 on export. The KB Metadatabyrån guidance makes these mandatory for Swedish cataloging." },
    ],
    realWorldExamples: [
      {
        scenario: "GMD to 336/337/338 migration chaos",
        problem: "A library catalog has 15 years of records with 245 $h [electronic resource] and newer records with 336 $a text + 337 $a computer + 338 $a online resource. The OPAC displays different material type labels depending on which fields are present, confusing users.",
        impact: "Faceted search by format produces inconsistent results because legacy and current records use different fields for the same information.",
      },
    ],
  },
  {
    id: "notes",
    label: "Notes",
    group: "descriptive",
    icon: "N",
    mappings: {
      unimarc: {
        field: "300-345 - Notes Block",
        label: "Notes",
        match: "exact",
        note: "UNIMARC uses 3XX block for notes. Each note type has a specific field. 300 for general notes, 320 for bibliography/index notes, 327 for contents notes.",
        subfields: [
          { code: "300 $a", desc: "General note (R)" },
          { code: "302 $a", desc: "Note on coded information (R)" },
          { code: "304 $a", desc: "Note relating to title and statement of responsibility (R)" },
          { code: "305 $a", desc: "Note relating to edition and bibliographic history (R)" },
          { code: "307 $a", desc: "Note relating to physical description (R)" },
          { code: "311 $a", desc: "Note relating to linking fields (R)" },
          { code: "320 $a", desc: "Bibliography/index note (R)" },
          { code: "327 $a", desc: "Contents note (R)" },
          { code: "330 $a", desc: "Summary or abstract (R)" },
          { code: "345 $a", desc: "Acquisition information note (R)" },
        ],
      },
      marc21: {
        field: "500-588 - Note Fields (5XX Block)",
        label: "Notes",
        match: "exact",
        note: "Extensive note block. Each note type has a dedicated field. Key fields: 500 (General), 504 (Bibliography), 505 (Contents), 520 (Summary), 546 (Language), 588 (Source of description).",
        subfields: [
          { code: "500 $a", desc: "General note (R)" },
          { code: "502 $a", desc: "Dissertation note (R)" },
          { code: "504 $a", desc: "Bibliography, etc. note (R)", note: "e.g., 'Includes bibliographical references (p. 230-245) and index'" },
          { code: "505 $a", desc: "Formatted contents note (R)", note: "ind1: 0=Complete; 1=Incomplete; 2=Partial; ind2: #=basic; 0=enhanced" },
          { code: "505 $t", desc: "Title within contents (R)", note: "Enhanced contents note" },
          { code: "505 $r", desc: "Statement of responsibility (R)" },
          { code: "520 $a", desc: "Summary, etc. (R)", note: "ind1: #=summary; 1=review; 2=scope; 3=abstract; 4=content advice" },
          { code: "546 $a", desc: "Language note (R)" },
          { code: "588 $a", desc: "Source of description note (R)", note: "Required in RDA" },
        ],
      },
      dc: {
        field: "dc:description",
        label: "Description",
        match: "lossy",
        note: "All note types collapse into dc:description. The distinction between a bibliography note, contents note, and summary is lost. Qualified DC adds dcterms:abstract and dcterms:tableOfContents.",
        elements: [
          { code: "dc:description", desc: "Account of the resource" },
          { code: "dcterms:abstract", desc: "Summary of the resource (Qualified DC)" },
          { code: "dcterms:tableOfContents", desc: "List of subunits (Qualified DC)" },
        ],
      },
      rda: {
        field: "RDA 7.x - Content Description",
        label: "Various content description elements",
        match: "exact",
        note: "RDA distributes note content across multiple elements in chapters 7 and 25. Some are core elements.",
        elements: [
          { code: "7.10", desc: "Summarization of the content" },
          { code: "7.16", desc: "Supplementary content", note: "Bibliographies, indexes, etc." },
          { code: "7.12", desc: "Language of the content" },
          { code: "25.1", desc: "Related work", note: "For contents notes linking to separate works" },
          { code: "2.17", desc: "Note on manifestation" },
          { code: "2.20", desc: "Note on resource description", note: "Source of description" },
        ],
      },
      bibframe: {
        field: "bf:note / bf:summary / bf:tableOfContents",
        label: "Notes and content description",
        match: "exact",
        note: "BIBFRAME types notes through distinct properties. More structured than MARC 5XX but less granular — many MARC note types map to generic bf:note.",
        elements: [
          { code: "bf:note", desc: "General note (property on any resource)" },
          { code: "bf:Note", desc: "Note class" },
          { code: "bf:summary", desc: "Summary/abstract (property on Work)" },
          { code: "bf:Summary", desc: "Summary class" },
          { code: "bf:tableOfContents", desc: "Contents note (property on Work)" },
          { code: "bf:TableOfContents", desc: "Table of contents class" },
          { code: "bf:supplementaryContent", desc: "Bibliography/index info (on Work)" },
          { code: "bf:dissertation", desc: "Dissertation info (on Work)" },
        ],
      },
    },
    systemNotes: [
      { system: "Koha", issue: "Koha indexes 505 $t (contents titles) separately for searching, which is powerful for anthologies. But if contents are entered in 505 $a as a single string instead of using enhanced format ($t/$r), individual titles are not separately searchable." },
      { system: "Libris XL", issue: "Libris XL maps most MARC 5XX notes to a generic 'Anmärkning' (Note) property. Some specific note types (520 summary, 505 contents) have dedicated properties, but many nuanced MARC note types flatten into the generic note on round-trip." },
    ],
    realWorldExamples: [
      {
        scenario: "Enhanced contents note in cross-system migration",
        problem: "A library has cataloged an anthology with enhanced 505 contents: $t Title one / $r Author one $t Title two / $r Author two (20 entries). During system migration the MARC is preserved, but the new OPAC template may switch from enhanced to basic display, showing the contents as an unformatted text wall.",
        impact: "Individual work titles and authors within the anthology lose their visual structure, reducing discoverability of contributions.",
      },
    ],
  },
  {
    id: "subject",
    label: "Subject",
    group: "subject",
    icon: "S",
    mappings: {
      unimarc: {
        field: "600-608 - Subject Access Fields (R)",
        label: "Subject access fields",
        match: "exact",
        note: "Each subject type has its own field. IFLA standard uses $2 for thesaurus source code.",
        indicators: [
          { pos: "606 ind1", label: "Level of subject term", values: "# = Not specified; 0 = Not applicable; 1 = Primary; 2 = Secondary" },
        ],
        subfields: [
          { code: "600 $a", desc: "Personal name subject (NR)" },
          { code: "601 $a", desc: "Corporate name subject (NR)" },
          { code: "602 $a", desc: "Family name subject (NR)" },
          { code: "604", desc: "Author/title subject (NR)" },
          { code: "605 $a", desc: "Title used as subject (NR)" },
          { code: "606 $a", desc: "Topical subject (NR)" },
          { code: "606 $x", desc: "Topical subdivision (R)" },
          { code: "606 $y", desc: "Geographical subdivision (R)" },
          { code: "606 $z", desc: "Chronological subdivision (R)" },
          { code: "607 $a", desc: "Geographical name subject (NR)" },
          { code: "608 $a", desc: "Form/genre heading (NR)" },
          { code: "6XX $2", desc: "System code (NR)", note: "rameau, lcsh, sao, etc." },
          { code: "6XX $3", desc: "Authority record identifier (NR)" },
        ],
      },
      marc21: {
        field: "600-651, 653, 655",
        label: "Subject access fields",
        match: "exact",
        note: "Second indicator specifies thesaurus: 0=LCSH, 1=LC Children's, 2=MeSH, 4=source not specified, 7=source in $2.",
        indicators: [
          { pos: "650 ind1", label: "Level of subject", values: "# = No info; 0 = No level specified; 1 = Primary; 2 = Secondary" },
          { pos: "650 ind2", label: "Thesaurus", values: "0 = LCSH; 1 = LC Children's; 2 = MeSH; 4 = Source not specified; 7 = Source in $2" },
        ],
        subfields: [
          { code: "600 $a", desc: "Personal name subject (NR)" },
          { code: "610 $a", desc: "Corporate name subject (NR)" },
          { code: "611 $a", desc: "Meeting name subject (NR)" },
          { code: "630 $a", desc: "Uniform title subject (NR)" },
          { code: "648 $a", desc: "Chronological term (NR)" },
          { code: "650 $a", desc: "Topical term (NR)" },
          { code: "650 $v", desc: "Form subdivision (R)" },
          { code: "650 $x", desc: "General subdivision (R)" },
          { code: "650 $y", desc: "Chronological subdivision (R)" },
          { code: "650 $z", desc: "Geographic subdivision (R)" },
          { code: "651 $a", desc: "Geographic name subject (NR)" },
          { code: "655 $a", desc: "Genre/form term (NR)" },
          { code: "6XX $2", desc: "Source of heading (NR)", note: "sao, lcsh, mesh, saogf, etc." },
          { code: "6XX $0", desc: "Authority record control number or URI (R)" },
        ],
      },
      dc: {
        field: "dc:subject",
        label: "Subject",
        match: "lossy",
        note: "All subject types collapse into dc:subject. Thesaurus source may be indicated with a scheme qualifier but often isn't.",
        elements: [
          { code: "dc:subject", desc: "Topic of the resource" },
          { code: "dcterms:LCSH", desc: "Encoding scheme (Qualified DC)" },
          { code: "dcterms:MeSH", desc: "Encoding scheme (Qualified DC)" },
          { code: "dcterms:spatial", desc: "Spatial characteristics (Qualified DC)", note: "May overlap with geographic subject" },
          { code: "dcterms:temporal", desc: "Temporal characteristics (Qualified DC)" },
        ],
      },
      rda: {
        field: "RDA 23.1",
        label: "Subject relationship",
        match: "partial",
        note: "RDA defines the subject relationship broadly and defers to vocabulary standards (LCSH, SAO, etc.).",
        elements: [
          { code: "23.1", desc: "Subject of the work" },
          { code: "23.4", desc: "Subject relationship designator" },
        ],
      },
      bibframe: {
        field: "bf:subject",
        label: "Subject",
        match: "partial",
        note: "BIBFRAME uses typed subject resources. Retains type distinction lost in Dublin Core.",
        elements: [
          { code: "bf:subject", desc: "Subject property (on Work)" },
          { code: "bf:Topic", desc: "Topical subject (class)" },
          { code: "bf:Place", desc: "Geographic subject (class)" },
          { code: "bf:Temporal", desc: "Chronological subject (class)" },
          { code: "bf:Person", desc: "Personal name subject (class)" },
          { code: "bf:Organization", desc: "Corporate name subject (class)" },
          { code: "bf:source", desc: "Source vocabulary (property)", note: "Links to vocabulary URI" },
        ],
      },
    },
    systemNotes: [
      {
        system: "Koha",
        issue: "Koha's authority plugin for 650 works well with LCSH but support for Svenska ämnesord (SAO) requires custom configuration. The $2 subfield must contain 'sao' and the authority framework must be configured separately.",
      },
      {
        system: "Libris XL → Koha",
        issue: "Libris XL stores SAO headings as linked URIs (id.kb.se). Exporting to MARC 21 for Koha flattens these to text in 650 $a with $2 sao, but the URI in $0 may not resolve in Koha's authority module.",
      },
    ],
    realWorldExamples: [
      {
        scenario: "Swedish subject headings in an international context",
        problem: "A Swedish library record uses 650 _7 $a Klimatförändringar $2 sao (Svenska ämnesord). When harvested via OAI-PMH into Europeana as dc:subject, the thesaurus source is lost. A French user sees 'Klimatförändringar' with no indication it's a Swedish controlled term and no link to the equivalent LCSH 'Climatic changes'.",
        impact: "Cross-language subject discovery fails because the vocabulary context is stripped during the crosswalk.",
      },
      {
        scenario: "SAO vs LCSH: structural differences in compound headings",
        problem: "LCSH uses pre-coordinated headings with subdivisions: '650 _0 $a Libraries $x Special collections $x Children\\'s literature'. SAO uses a flatter structure: '650 _7 $a Barnlitteratur $2 sao' and '650 _7 $a Bibliotek $x Specialsamlingar $2 sao' as two separate headings. When a record has both SAO and LCSH headings and is crosswalked to Dublin Core, the structural logic of both systems is lost — all subdivisions become flat text strings.",
        impact: "The carefully constructed hierarchy of LCSH subdivisions and the deliberate simplicity of SAO headings both dissolve into undifferentiated dc:subject entries, making post-coordinated search the only option.",
      },
      {
        scenario: "SAO heading with no LCSH equivalent",
        problem: "SAO contains headings specific to Swedish contexts that have no direct LCSH match — for example, 'Allemansrätten' (the Swedish right of public access to nature). LCSH has no equivalent heading. When merging Swedish and American library catalogs, these culturally specific headings either get dropped or mapped to a broader LCSH term like 'Right of property' which misrepresents the concept entirely.",
        impact: "Culturally specific knowledge is either lost or distorted when forced into a vocabulary designed for a different legal and cultural context.",
      },
    ],
  },
  {
    id: "classification",
    label: "Classification",
    group: "subject",
    icon: "C",
    mappings: {
      unimarc: {
        field: "675 (UDC) / 676 (DDC) / 680 (LC)",
        label: "Classification numbers",
        match: "exact",
        note: "Each classification system has its own field. National implementations prioritize different systems.",
        indicators: [
          { pos: "675 ind", label: "Undefined", values: "# # (blank)" },
          { pos: "676 ind1", label: "Type of edition", values: "# = No info; 0 = Full edition; 1 = Abridged" },
        ],
        subfields: [
          { code: "675 $a", desc: "UDC notation (NR)" },
          { code: "675 $v", desc: "Edition identifier (NR)" },
          { code: "675 $z", desc: "Language of edition (NR)" },
          { code: "676 $a", desc: "DDC number (NR)" },
          { code: "676 $v", desc: "Edition of DDC (NR)" },
          { code: "680 $a", desc: "LCC class number (NR)" },
          { code: "680 $b", desc: "Book number (NR)" },
          { code: "686 $a", desc: "Other classification number (NR)", note: "For SAB and other national systems" },
          { code: "686 $2", desc: "System code (NR)", note: "Identifies the classification scheme" },
        ],
      },
      marc21: {
        field: "080 (UDC) / 082 (DDC) / 050 (LC)",
        label: "Classification numbers",
        match: "exact",
        note: "SAB classification stored in 084 $a with $2 kssb/8 (8th edition).",
        indicators: [
          { pos: "082 ind1", label: "Type of edition", values: "0 = Full; 1 = Abridged; 7 = Other in $2" },
          { pos: "082 ind2", label: "Source", values: "# = No info; 0 = Assigned by LC; 4 = Other agency" },
          { pos: "050 ind1", label: "In LC collection", values: "# = No info; 0 = In LC; 1 = Not in LC" },
          { pos: "050 ind2", label: "Source", values: "0 = Assigned by LC; 4 = Other agency" },
        ],
        subfields: [
          { code: "050 $a", desc: "Classification number (R)" },
          { code: "050 $b", desc: "Item number (NR)" },
          { code: "080 $a", desc: "UDC number (NR)" },
          { code: "080 $2", desc: "Edition identifier (NR)" },
          { code: "082 $a", desc: "DDC number (R)" },
          { code: "082 $b", desc: "Item number (NR)" },
          { code: "082 $2", desc: "Edition number (NR)" },
          { code: "084 $a", desc: "Classification number (R)", note: "SAB, BBK, other national systems" },
          { code: "084 $2", desc: "Source of number (NR)", note: "e.g., kssb/8 for SAB 8th ed." },
        ],
      },
      dc: {
        field: "dc:subject (with scheme)",
        label: "Subject",
        match: "lossy",
        note: "No dedicated classification element. Notations go into dc:subject — conflating notation with natural-language headings.",
        elements: [
          { code: 'dc:subject xsi:type="dcterms:DDC"', desc: "DDC notation as subject (Qualified DC)" },
          { code: 'dc:subject xsi:type="dcterms:UDC"', desc: "UDC notation as subject (Qualified DC)" },
          { code: 'dc:subject xsi:type="dcterms:LCC"', desc: "LCC notation as subject (Qualified DC)" },
        ],
      },
      rda: {
        field: "RDA 6.2 (classification)",
        label: "Not directly addressed",
        match: "none",
        note: "RDA focuses on description and access, not classification. Libraries using RDA still assign DDC/UDC/SAB independently.",
        elements: [],
      },
      bibframe: {
        field: "bf:classification",
        label: "Classification",
        match: "exact",
        note: "BIBFRAME has typed subclasses for major systems. Notation and edition are separate properties — structurally clean.",
        elements: [
          { code: "bf:Classification", desc: "Classification superclass" },
          { code: "bf:ClassificationDdc", desc: "DDC classification (subclass)" },
          { code: "bf:ClassificationLcc", desc: "LCC classification (subclass)" },
          { code: "bf:ClassificationUdc", desc: "UDC classification (subclass)" },
          { code: "bf:ClassificationNlm", desc: "NLM classification (subclass)" },
          { code: "bf:classificationPortion", desc: "Classification number (property)" },
          { code: "bf:itemPortion", desc: "Item number (property)" },
          { code: "bf:edition", desc: "Edition of scheme (property)" },
          { code: "bf:source", desc: "Source (property)", note: "For systems like SAB not in named subclasses" },
        ],
      },
    },
    classificationSystems: {
      sab: {
        label: "SAB (Klassifikationssystem för svenska bibliotek)",
        note: "Used in Swedish public and academic libraries. Stored in MARC 21 as 084 $a with $2 kssb/8 (8th edition). Hierarchical structure with main classes A-Ö. No direct equivalent in UNIMARC — requires local field or 686.",
        example: "Hc = Bibliografi, Hca = Nationalbibliografi",
      },
      ddc: {
        label: "DDC (Dewey Decimal Classification)",
        note: "Internationally used. UNIMARC 676, MARC 21 082. Notation is numeric (000-999) with decimal expansion. Well-supported across all systems.",
        example: "025.3 = Cataloguing and classification",
      },
      udc: {
        label: "UDC (Universal Decimal Classification)",
        note: "Used extensively in Southern Europe, Central Europe, and many UNIMARC-based libraries worldwide. UNIMARC 675, MARC 21 080. More expressive syntax than DDC (colon for relation, plus sign for addition, double colon for order-fixing). Widely used for shelf classification in academic libraries.",
        example: "025.4 = Subject analysis. Classification. Indexing",
      },
    },
    systemNotes: [
      {
        system: "Libris XL",
        issue: "SAB classification is core to Swedish library practice. Libris XL stores SAB in 084 with $2 kssb/8. When a Swedish library exports to an international aggregator, SAB numbers mean nothing without the code list — and most aggregators don't carry it.",
      },
      {
        system: "Koha (Swedish libraries)",
        issue: "Koha has no built-in SAB validation. Classification numbers in 084 are free text — typos in SAB notation (e.g., 'Hc.01' instead of 'Hc.01') are not caught, unlike DDC which has the classification plugin.",
      },
      {
        system: "UNIMARC → MARC 21 (Alma)",
        issue: "Portuguese UDC numbers in UNIMARC 675 map to MARC 21 080, but the $v (edition) subfield mapping can be inconsistent. Some conversions lose the UDC edition indicator, making it impossible to know which UDC edition was used.",
      },
    ],
    realWorldExamples: [
      {
        scenario: "SAB classification in Dublin Core export",
        problem: "A Swedish academic library exports records to a European aggregator via OAI-PMH. The SAB number 'Qb' (physics) ends up in dc:subject alongside the Swedish subject heading 'Fysik'. The aggregator cannot distinguish the classification notation from the subject term, so 'Qb' appears as a browsable subject — confusing users.",
        impact: "Classification notations pollute the subject browse when crosswalked without type distinction.",
      },
    ],
  },
  {
    id: "genre",
    label: "Genre / Form",
    group: "subject",
    icon: "G",
    mappings: {
      unimarc: {
        field: "608 $a",
        label: "Form, genre heading",
        match: "exact",
        note: "Less widely adopted than MARC 21's 655 — many UNIMARC implementations use 606 for genre terms instead.",
        indicators: [
          { pos: "1", label: "Undefined", values: "# (blank)" },
          { pos: "2", label: "Undefined", values: "# (blank)" },
        ],
        subfields: [
          { code: "$a", desc: "Entry element (NR)" },
          { code: "$j", desc: "Form subdivision (R)" },
          { code: "$x", desc: "Topical subdivision (R)" },
          { code: "$y", desc: "Geographical subdivision (R)" },
          { code: "$z", desc: "Chronological subdivision (R)" },
          { code: "$2", desc: "System code (NR)", note: "Source vocabulary" },
          { code: "$3", desc: "Authority record identifier (NR)" },
        ],
      },
      marc21: {
        field: "655 $a",
        label: "Index term — genre/form",
        match: "exact",
        note: "Growing in importance with the separation of 'about-ness' (650 topical) from 'is-ness' (655 genre/form).",
        indicators: [
          { pos: "1", label: "Type of heading", values: "# = Basic; 0 = Faceted" },
          { pos: "2", label: "Thesaurus", values: "0 = LCSH (pre-LCGFT); 4 = Source not specified; 7 = Source in $2" },
        ],
        subfields: [
          { code: "$a", desc: "Genre/form data or focus term (NR)" },
          { code: "$b", desc: "Non-focus term (R)" },
          { code: "$c", desc: "Facet/hierarchy designation (R)" },
          { code: "$v", desc: "Form subdivision (R)" },
          { code: "$x", desc: "General subdivision (R)" },
          { code: "$y", desc: "Chronological subdivision (R)" },
          { code: "$z", desc: "Geographic subdivision (R)" },
          { code: "$2", desc: "Source of term (NR)", note: "lcgft, saogf, fast, etc." },
          { code: "$0", desc: "Authority record control number or URI (R)" },
        ],
      },
      dc: {
        field: "dc:type",
        label: "Type",
        match: "partial",
        note: "dc:type with DCMI Type Vocabulary captures broad types but not specific genre/form. The granularity gap is enormous.",
        elements: [
          { code: "dc:type", desc: "Nature or genre of the resource" },
          { code: "DCMI Types", desc: "Collection, Dataset, Event, Image, Interactive Resource, Moving Image, Physical Object, Service, Software, Sound, Still Image, Text" },
        ],
      },
      rda: {
        field: "RDA 6.3 / 7.2",
        label: "Form of work / Content type",
        match: "partial",
        note: "RDA separates form of work from content type. Together they approximate MARC 655, but mapping is not one-to-one.",
        elements: [
          { code: "6.3", desc: "Form of work", note: "e.g., novel, poem, play, film" },
          { code: "7.2", desc: "Content type (Core)", note: "text, performed music, cartographic image, etc." },
          { code: "7.3", desc: "Media type (Core)", note: "audio, computer, microform, unmediated, video" },
          { code: "7.4", desc: "Carrier type (Core)", note: "online resource, volume, audio disc, etc." },
        ],
      },
      bibframe: {
        field: "bf:genreForm",
        label: "Genre/Form",
        match: "exact",
        note: "bf:GenreForm as a typed resource linking to vocabulary URIs (LCGFT, SAOGF). Clean mapping from MARC 655.",
        elements: [
          { code: "bf:genreForm", desc: "Genre/form property (on Work or Instance)" },
          { code: "bf:GenreForm", desc: "Genre/form class" },
          { code: "bf:source", desc: "Source vocabulary (property)", note: "Links to LCGFT, SAOGF, etc." },
          { code: "bf:content", desc: "Content type (separate from genre)" },
          { code: "bf:media", desc: "Media type" },
          { code: "bf:carrier", desc: "Carrier type" },
        ],
      },
    },
    systemNotes: [
      {
        system: "Koha",
        issue: "Koha's advanced search has no dedicated genre/form facet by default. 655 data is indexed but libraries need to configure a custom search index and OPAC facet to make genre/form browsable.",
      },
      {
        system: "Libris XL",
        issue: "Libris XL supports SAOGF (Svenska ämnesord — genre/form) in 655 with $2 saogf. Genre/form is well-integrated in the discovery interface. However, older records may have genre terms in 650 (topical) instead of 655.",
      },
    ],
    realWorldExamples: [
      {
        scenario: "Genre vs. subject confusion in legacy data",
        problem: "Pre-2010 MARC 21 records often coded 'Science fiction' as a 650 topical subject instead of a 655 genre/form. When these records are crosswalked, 'Science fiction' appears as a topic (what the book is ABOUT) rather than a form (what the book IS). A search for 'books about science fiction' returns science fiction novels, which is wrong.",
        impact: "The about/is distinction — fundamental to modern cataloging — is silently corrupted in legacy crosswalks.",
      },
    ],
  },
];
